Algoritmo "Olá, Mundo!"
// Disciplina   : Algoritmos e Lógica de Programação
// Professor   : Gustavo Guanabara 
// Descrição   : Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
// Autor(a)    : Bernardo A. Carvalho
// Data atual  : 11/04/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Olá, Mundo!")

Fimalgoritmo