Algoritmo "Informações funcionário"
// Disciplina   : Algoritmos e Lógica de Programação
// Professor   : Gustavo Guanabara 
// Descrição   : Crie um programa que leia o nome
// e o salário de um funcionário, mostrando no final uma mensagem.
// Autor(a)    : Bernardo A. Carvalho
// Data atual  : 13/04/2026
Var
// Seção de Declarações das variáveis 
nome: caractere
salario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
salario <- 1850.45
Escreva("Nome do Funcionário: ")
Leia(nome)
Escreva("O(a) funcionário(a) ", nome, " tem um salário de R$", salario, " em Junho.")

Fimalgoritmo